version: '2'
services:
  solr:
    image: solr
    ports:
      - "8983:8983"
  redis:
    image: redis
  web:
    build: ./build/apache
    ports:
      - "5000:80"
    links:
      - solr
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./drupal-7.53:/var/www/html
